export default Object.freeze({
  langSelect: 'Choose Language',
  intro: 'Introduction',
  inventoryHome: 'InventoryScreen',
  sales: 'SalesHome',
  addItem: 'Add Item',
  saleDetails: 'saleDetail',
  salesNav: 'Sales',
  expensesNav: 'Expense',
  newSale: 'NewSale',
  expenses: 'Expenses',
  plan: 'Plan',
  introNav: 'Intro',
  Gebi: 'Gebi',
  itemDetails: 'Item Details',
  EditItem: 'Edit Item',
  inventoryNav: 'Inventory',
  login: 'Login',
  register: 'Register',
  otp: 'OTP-Auth',
  register: 'Register',
  settingsNav: 'SettingsNav',
  settings: 'Settings Home',
  selectLanguage: 'Select Language',
});
