export default Object.freeze({
  langSelect: 'Choose Language',
  intro: 'Introduction',
  inventory: 'InventoryScreen',
  sales: 'Sales',
  salesNav: 'ሽያጭ',
  newSale: 'NewSale',
  expenses: 'Expenses',
  plan: 'Plan',
  introNav: 'Intro',
  appNav: 'Home',
  itemDetails: 'Item Details',
  EditItem: 'Edit Item',
  inventoryNav: 'አቃ ክፍል',
  login: 'Login',
  register: 'Register',
  otp: 'OTP-Auth',
  register: 'Register',
});
