export default Object.freeze({
  authNavigator: 'authNavigator',
  mainNavigator: 'mainNavigator',
  langSelect: 'Choose Language',
  intro: 'Introduction',
  homeScreen: 'homeScreen',
  inventoryHome: 'InventoryScreen',
  addNewExpense: 'addNewExpense',
  sales: 'SalesHome',
  addItem: 'Add Item',
  categoryNav: 'categoryNav',
  categories: 'Categories',
  addNewCategory: 'Add Category',
  saleDetails: 'saleDetails',
  salesNav: 'Sales',
  expensesNav: 'Expense',
  newSale: 'NewSale',
  expenses: 'Expenses',
  plan: 'Plan',
  introNav: 'Intro',
  Gebi: 'Gebi',
  itemDetails: 'Item Details',
  EditItem: 'Edit Item',
  addNewItem: 'Add New Item',
  inventoryNav: 'Inventory',
  login: 'Login',
  register: 'Register',
  confirmation: 'Confirm',
  otp: 'OTP-Auth',
  settingsNav: 'SettingsNav',
  settings: 'Settings Home',
  selectLanguage: 'Select Language',
  editProfile: 'editProfile',
  addEmployee: 'New Employee',
  editEmployee: 'Edit Employee',
  subscriptions: 'Subscriptions',
});
